package com.back.simpleDb;
import org.gradle.internal.impldep.org.intellij.lang.annotations.MagicConstant;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.*;

public class Sql {
    private final SimpleDb simpleDb;
    private final StringBuilder clauses = new StringBuilder();
    private final List<Object> keywords = new ArrayList<>();

    public Sql(SimpleDb simpleDb) {
        this.simpleDb = simpleDb;
    }

    public Sql append(String clause, Object ...args) {
        clauses.append(clause).append(" ");
        keywords.addAll(Arrays.asList(args));

        return this;
    }

    public Sql appendIn(String clause, Object ...args) {

        StringBuilder sb = new StringBuilder("?");
        for (int i = 0 ; i<args.length-1 ; i++) {
            sb.append(", ").append("?");
        }
        String trans = clause.replace("?", sb.toString());

        return append(trans, args);
    }


    public PreparedStatement prepareStatement() throws SQLException {
        return prepareStatement(Statement.NO_GENERATED_KEYS);
    }

    public PreparedStatement prepareStatement(
        @MagicConstant(intValues = {Statement.RETURN_GENERATED_KEYS,Statement.NO_GENERATED_KEYS}) int autoGeneratedKeys
    ) throws SQLException {
        Connection conn = simpleDb.getConnection();

        PreparedStatement ps = conn.prepareStatement(clauses.toString(), autoGeneratedKeys);

        for (int i = 0; i < keywords.size(); i++) {
            ps.setObject(i + 1, keywords.get(i));
        }

        return ps;
    }

    public int insert() {
        try (PreparedStatement ps = prepareStatement(Statement.RETURN_GENERATED_KEYS)) {
            ps.executeUpdate();

            ResultSet rs = ps.getGeneratedKeys();
            if (rs.next()) return rs.getInt(1);
            else throw new RuntimeException("키 가져올 수 없음");

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public int update() {
        try (PreparedStatement ps = prepareStatement()) {
            return ps.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public int delete() {
        try (PreparedStatement ps = prepareStatement()) {
            return ps.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public Map<String, Object> selectRow() {
        return selectRows().getFirst();
    }

    public List<Map<String, Object>> selectRows() {
        try (PreparedStatement ps = prepareStatement()) {

            ResultSet resultSet = ps.executeQuery();
            ResultSetMetaData metaData = resultSet.getMetaData();

            List<Map<String, Object>> records = new ArrayList<>();
            while(resultSet.next()) {
                Map<String, Object> row = new HashMap<>();
                for (int i=1 ; i<= metaData.getColumnCount() ; i++) {
                    row.put(metaData.getColumnName(i), resultSet.getObject(i));
                }

                records.add(row);
            }

            return records;

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public <T> T selectRow(Class<T> clazz) {
        return selectRows(clazz).getFirst();
    }

    public <T> List<T> selectRows(Class<T> clazz) {
        try (PreparedStatement ps = prepareStatement()) {

            ResultSet resultSet = ps.executeQuery();
            ResultSetMetaData metaData = resultSet.getMetaData();


            List<T> records = new ArrayList<>();
            while(resultSet.next()) {
                T obj = clazz.getDeclaredConstructor().newInstance();

                for (int i=1 ; i<= metaData.getColumnCount() ; i++) {
                    String name = metaData.getColumnLabel(i);
                    Object value = resultSet.getObject(i);

                    Field field = clazz.getDeclaredField(name);
                    field.setAccessible(true);
                    field.set(obj, value);
                }

                records.add(obj);
            }

            return records;

        } catch (SQLException | NoSuchFieldException | InvocationTargetException | InstantiationException |
                 IllegalAccessException | NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
    }

    public LocalDateTime selectDatetime() {
        try (PreparedStatement ps = prepareStatement()) {

            ResultSet rs = ps.executeQuery();
            rs.next();
            return rs.getTimestamp(1).toLocalDateTime();


        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public Long selectLong() {
        return selectLongs().getFirst();
    }

    public List<Long> selectLongs() {
        try (PreparedStatement ps = prepareStatement()) {

            ResultSet rs = ps.executeQuery();

            List<Long> ids =  new ArrayList<>();
            while(rs.next()) {
                ids.add(rs.getLong(1));
            }
            return ids;

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public String selectString() {
        try (PreparedStatement ps = prepareStatement()) {

            ResultSet rs = ps.executeQuery();
            rs.next();
            return rs.getString(1);


        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public Boolean selectBoolean() {
        try (PreparedStatement ps = prepareStatement()) {

            ResultSet rs = ps.executeQuery();
            rs.next();
            return rs.getBoolean(1);


        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }



}
